Genre.delete_all

Genre.create( title: 'Action',          description: 'Action film is a film genre in which one or more heroes are thrust into a series of challenges in which physical feats, extended fights and frenetic chases are required.' )
Genre.create( title: 'Animation',       description: 'Animation is the rapid display of a sequence of images to create an illusion of movement.' ) 
Genre.create( title: 'Biopics',         description: 'A film that dramatizes the life of an actual person or people.' )
Genre.create( title: 'Bollywood',       description: 'Bollywood is the informal term popularly used for the Hindi-language film industry based in Mumbai.' )
Genre.create( title: 'Comedy',          description: 'Comedy film is a genre of film in which the main emphasis is on humour.' )
Genre.create( title: 'Crime',           description: 'Crime films are films which focus on the lives of criminals.' )
Genre.create( title: 'Documentary',     description: 'Documentary films constitute a broad category of nonfictional motion pictures intended to document some aspect of reality, primarily for the purposes of instruction or maintaining a historical record.' )
Genre.create( title: 'Drama',           description: 'A drama film is a film genre that depends mostly on in-depth development of realistic characters dealing with emotional themes.' )
Genre.create( title: 'Family',          description: 'A motion picture that contain children or relates to them in the context of home and family.' )
Genre.create( title: 'Film Noir',       description: 'Film noir is a cinematic term used primarily to describe stylish Hollywood crime dramas, particularly those that emphasize cynical attitudes and sexual motivations.' )
Genre.create( title: 'Foreign',         description: 'World cinema is a term used primarily in English language speaking countries to refer to the films and film industries of non-English speaking countries.' )
Genre.create( title: 'Horror',          description: "Horror is a film genre seeking to elicit a negative emotional reaction from viewers by playing on the audience's primal fears." )
Genre.create( title: 'Musical',         description: 'A film genre in which songs sung by the characters are interwoven into the narrative, sometimes accompanied by dancing.' )
Genre.create( title: 'Romance',         description: 'Romance films (or romance movies) are romantic love stories recorded in visual media for broadcast in theaters and on television that focus on passion, emotion, and the affectionate romantic involvement of the main characters and the journey that their genuinely strong, true and pure romantic love takes them through dating, courtship or marriage.' )
Genre.create( title: 'Science Fiction', description: 'Science fiction film is a film genre that uses science fiction: speculative, science-based depictions of phenomena that are not necessarily accepted by mainstream science, such as extraterrestrial life forms, alien worlds, extrasensory perception, and time travel, often along with futuristic elements such as spacecraft, robots, cyborgs, interstellar space travel or other technologies.' )
Genre.create( title: 'Thriller',        description: 'Thriller is a broad genre of literature, film, and television programming that uses suspense, tension and excitement as the main elements.' )
Genre.create( title: 'War',             description: 'War films are a film genre concerned with warfare, usually about naval, air or land battles, sometimes focusing instead on prisoners of war, covert operations, military training or other related subjects.' )
Genre.create( title: 'Westerns',        description: 'The Western is a genre of various arts, such as film, television, radio, literature, painting and others.' )
